apiVersion: v1
kind: Pod
metadata:
  name: react-test-app-pod
  labels:
    component: web
spec:
  containers:
    - name: react-test-app
      image: or11/react-test-app:0feb317
      ports:
        - containerPort: 3000