apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-test-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: react-test-app
          image: or11/react-test-app:d66c103
          ports:
            - containerPort: 3000
          env:
            - name: PGHOST
              value: posgres-cluster-ip-service
            - name: PGPORT
              value: '5432'
            - name: PGUSER
              value: postgres
            - name: PGDATABASE
              value: postgres
            # - name: PGPASSWORD # not used in this deployment
            #   valueFrom:
            #     secretKeyRef:
            #       name: pgpassword # name of the secret object
            #       key: PGPASSWORD # (one of the keynames) inside of the secret object