apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-test-deploy-react-test-app-run
spec:
  pipelineRef:
    name: build-test-deploy-react-test-app
  resources:
  - name: git
    resourceRef:
      name: react-test-app-fork-git
