apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  # The name of the pipeline resource
  name: react-test-app-fork-git
spec:
  type: git
  params:
  # The revision/branch of the repository
  - name: revision
    value: main
  # The URL of the repository
  - name: url
    value: https://github.com/OR1-1/react-test-app-fork
